// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLL-kaSmSR3ZmW-Kp_GVxqMnJ3OG2VmSw',
    appId: '1:800504157486:web:9b84aadd591923832a96bf',
    messagingSenderId: '800504157486',
    projectId: 'newproject-18239',
    authDomain: 'newproject-18239.firebaseapp.com',
    storageBucket: 'newproject-18239.firebasestorage.app',
    measurementId: 'G-BF99YSVQPL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBeyIsBaI65W9a3QmDjOKZLqneGq_oJojM',
    appId: '1:800504157486:android:7acf50fb98f091e72a96bf',
    messagingSenderId: '800504157486',
    projectId: 'newproject-18239',
    storageBucket: 'newproject-18239.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1Ro1ShZR-FPJXNSnWiTA1VXR-NuE80yU',
    appId: '1:800504157486:ios:a9b685f98a7b59382a96bf',
    messagingSenderId: '800504157486',
    projectId: 'newproject-18239',
    storageBucket: 'newproject-18239.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1Ro1ShZR-FPJXNSnWiTA1VXR-NuE80yU',
    appId: '1:800504157486:ios:a9b685f98a7b59382a96bf',
    messagingSenderId: '800504157486',
    projectId: 'newproject-18239',
    storageBucket: 'newproject-18239.firebasestorage.app',
    iosBundleId: 'com.example.newProject',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLL-kaSmSR3ZmW-Kp_GVxqMnJ3OG2VmSw',
    appId: '1:800504157486:web:f49726cf147476f42a96bf',
    messagingSenderId: '800504157486',
    projectId: 'newproject-18239',
    authDomain: 'newproject-18239.firebaseapp.com',
    storageBucket: 'newproject-18239.firebasestorage.app',
    measurementId: 'G-6NHP8G3CKC',
  );
}
